# Generated by Django 2.2.4 on 2019-09-14 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_department_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('project_grade', models.CharField(choices=[('A', 'Very Good'), ('B', 'Good'), ('C', 'Average'), ('D', 'Pass'), ('F', 'Fail'), ('IC', 'Incomplete')], max_length=30)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.StudentProfile')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.TutorProfile')),
            ],
        ),
    ]
